import * as $ from 'jquery'
import '@styles/scss.scss'
import '@styles/burger_menu.scss'
import '@media/header_footer.scss'
import '@media/indexMedia.scss'
import '@js/header-footer.js'
import '@buttons/buttons_style.scss'
